### ISSUE TITLE
missing implementation

### ISSUE THREAD

**Issue by dvolgyes** [nachifur-ljw/label_correction_based_CCESD#1]
Hi,

In the [arxiv paper](https://arxiv.org/pdf/2010.01919v1.pdf) you claim the implementation published here,
but it seems you forgot to submit it.

**Comment by nachifur-ljw** [comment]
Soory, The reminder email was automatically set as spam, so I didn’t see it in time. Thank you for your attention to our work. The paper is currently being revised and improved. I need some time to organize the code and dataset. Future articles will be updated further, we decided to use this link https://github.com/nachifur-ljw/automatic_label_correction_based_CCEDD.

**Comment by nachifur-ljw** [comment]
If you want to know the specific implementation, I can upload the **informal** code now. The release of the dataset will take some time. But without data, you can't run it, you can only understand the idea of the code.
